/**:
  ros__parameters:
    publish_robot_description_semantic: True
    publish_planning_scene: True
    publish_geometry_updates: True
    publish_state_updates: True
    publish_transforms_updates: True
    default_planning_pipeline: ompl

    planning_pipelines:
      pipeline_names: [ompl]

    capabilities: move_group/ExecuteTaskSolutionCapability
