controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    turntable_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

turntable_controller:
  ros__parameters:
    joints:
      - turntable_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

joint_state_broadcaster:
  ros__parameters:
    {}
